#!/usr/bin/env python3
"""Test DuckDB syntax for auto-incrementing primary keys."""

import os
import tempfile
import duckdb

# Create a temporary database
db_path = tempfile.mktemp(suffix='.duckdb')
print(f"Testing database: {db_path}")

# Test different syntaxes
syntaxes = [
    ("INTEGER PRIMARY KEY", "Standard INTEGER PRIMARY KEY"),
    ("BIGINT PRIMARY KEY", "BIGINT PRIMARY KEY"),
    ("SERIAL PRIMARY KEY", "SERIAL PRIMARY KEY"),
    ("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER PRIMARY KEY AUTOINCREMENT"),
    ("INTEGER PRIMARY KEY AUTO_INCREMENT", "INTEGER PRIMARY KEY AUTO_INCREMENT"),
    ("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "GENERATED BY DEFAULT AS IDENTITY"),
]

for i, (col_def, desc) in enumerate(syntaxes):
    print(f"\nTest {i+1}: {desc}")
    print(f"  Column definition: {col_def}")
    
    # Create fresh connection
    conn = duckdb.connect(db_path)
    
    # Drop table if exists
    conn.execute("DROP TABLE IF EXISTS test_table")
    
    # Try to create table
    try:
        conn.execute(f"""
            CREATE TABLE test_table (
                id {col_def},
                name TEXT
            )
        """)
        print(f"  Table created successfully")
        
        # Try to insert without id
        try:
            conn.execute("INSERT INTO test_table (name) VALUES (?)", ("Test Name",))
            print(f"  Insert without id: SUCCESS")
            
            # Query to see what id was generated
            result = conn.execute("SELECT id, name FROM test_table").fetchone()
            print(f"  Generated id: {result[0]}, name: {result[1]}")
        except Exception as e:
            print(f"  Insert without id: FAILED - {e}")
            
    except Exception as e:
        print(f"  Create table: FAILED - {e}")
    
    conn.close()
    
    # Clean up for next test
    if os.path.exists(db_path):
        os.remove(db_path)

print("\n--- Testing the correct syntax with multiple inserts ---")
# Use the syntax that worked
conn = duckdb.connect(db_path)
try:
    conn.execute("""
        CREATE TABLE test_table (
            id INTEGER PRIMARY KEY,
            name TEXT
        )
    """)
    print("Table created with INTEGER PRIMARY KEY")
    
    # Insert multiple rows without id
    for i in range(3):
        conn.execute("INSERT INTO test_table (name) VALUES (?)", (f"Name {i+1}",))
    
    # Query all rows
    results = conn.execute("SELECT id, name FROM test_table ORDER BY id").fetchall()
    print("Inserted rows:")
    for row in results:
        print(f"  id={row[0]}, name={row[1]}")
        
except Exception as e:
    print(f"Error: {e}")
finally:
    conn.close()
    if os.path.exists(db_path):
        os.remove(db_path)

print("\n--- Testing with our actual schema ---")
conn = duckdb.connect(db_path)
try:
    conn.execute("""
        CREATE TABLE bpos (
            id INTEGER PRIMARY KEY,
            name TEXT UNIQUE,
            me_level INTEGER,
            te_level INTEGER,
            location TEXT,
            category TEXT,
            materials_json TEXT
        )
    """)
    print("BPOS table created")
    
    # Insert without id
    conn.execute("""
        INSERT INTO bpos (name, me_level, te_level, location, category, materials_json)
        VALUES (?, ?, ?, ?, ?, ?)
    """, ('Test BPO', 5, 10, 'Test Location', 'test', '{}'))
    print("Insert successful")
    
    # Check the id
    result = conn.execute("SELECT id, name FROM bpos").fetchone()
    print(f"Generated id: {result[0]}, name: {result[1]}")
    
except Exception as e:
    print(f"Error: {e}")
finally:
    conn.close()
    if os.path.exists(db_path):
        os.remove(db_path)